imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@BenUserBundle/Resources/config/config.yml" }
    - { resource: "@BenUserBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    form:
        resources:
            - 'BenDoctorsBundle:Form:fields.html.twig'
            - 'VichUploaderBundle:Form:fields.html.twig'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        pathToWeb: "%kernel.root_dir%/../web"
        bootstrapCss: "/home/ubuntu/workspace/RecepcionPago/web/bootstrap/css/bootstrap.css"
        mainCss: "/home/ubuntu/workspace/RecepcionPago/web/css/main.css"
        layoutCss: "/home/ubuntu/workspace/RecepcionPago/web/css/layout.css"
    
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        options:
            1002:  "SET NAMES 'UTF8' COLLATE 'utf8_general_ci'"
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#vich uploader configuration
vich_uploader:
    db_driver: orm
    storage: file_system
    twig: true
    
    mappings:
        recepcion_pago_image:
            uri_prefix:         /RecepcionPago/web/uploads/recepcion_pago
            upload_destination: %kernel.root_dir%/../web/uploads/recepcion_pago
            namer:              vich_uploader.namer_origname
            
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true

#knp_snappy pdf bundle
knp_snappy:
    pdf:
        enabled:    true
        binary:     /home/ubuntu/workspace/wkhtmltox/bin/wkhtmltopdf
        options:    []