<?php

namespace Ben\DoctorsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoContratacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoContratacionRepository extends EntityRepository
{
}
